version: '3.9'
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    entrypoint: ["minio", "server", "--console-address", ":9090"]
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=passwordnyaAdmin
      - MINIO_VOLUMES=/data
    volumes:
      - minio_data:/data
volumes:
  minio_data: {}
